---
- name: Show EIGRP neighbors
  hosts: gns3_routers
  gather_facts: false

  tasks:
    - name: Show EIGRP neighbors
      cisco.ios.ios_command:
        commands:
          - show ip eigrp neighbors
      register: output

    - name: Display EIGRP neighbors
      ansible.builtin.debug:
        var: output.stdout_lines