---
- name: Show interface information
  hosts: gns3_routers
  gather_facts: false

  tasks:
    - name: Show interfaces
      cisco.ios.ios_command:
        commands:
          - show interfaces
      register: output

    - name: Display interface information
      ansible.builtin.debug:
        var: output.stdout_lines