---
- name: Show interface status
  hosts: gns3_routers
  gather_facts: false

  tasks:
    - name: Show interfaces
      cisco.ios.ios_command:
        commands:
          - show interfaces status
      register: output

    - name: Display interface status
      ansible.builtin.debug:
        var: output.stdout_lines