---
- name: Show NTP status
  hosts: gns3_routers
  gather_facts: false

  tasks:
    - name: Show NTP status
      cisco.ios.ios_command:
        commands:
          - show ntp status
      register: output

    - name: Display NTP status
      ansible.builtin.debug:
        var: output.stdout_lines