---
- name: Show interfaces
  hosts: gns3_routers
  gather_facts: false

  tasks:
    - name: Show IP interface brief
      cisco.ios.ios_command:
        commands:
          - show ip interface brief
      register: output

    - name: Display output
      ansible.builtin.debug:
        var: output.stdout_lines