---
- name: Show IP protocols
  hosts: gns3_routers
  gather_facts: false

  tasks:
    - name: Show IP protocols
      cisco.ios.ios_command:
        commands:
          - show ip protocols
      register: output

    - name: Display output
      ansible.builtin.debug:
        var: output.stdout_lines